# Large game simulation
play(board,Coordinate(12),'W')
play(board,Coordinate(21),'W')
play(board,Coordinate(22),'W')
play(board,Coordinate(23),'W')
play(board,Coordinate(24),'W')
play(board,Coordinate(42),'B')
play(board,Coordinate(31),'W')
play(board,Coordinate(32),'B')
play(board,Coordinate(33),'B')
play(board,Coordinate(34),'B')
play(board,Coordinate(35),'W')
play(board,Coordinate(41),'W')
play(board,Coordinate(43),'B')
play(board,Coordinate(44),'W')
play(board,Coordinate(51),'W')
play(board,Coordinate(52),'B')
play(board,Coordinate(53),'B')
play(board,Coordinate(55),'W')
play(board,Coordinate(62),'W')
play(board,Coordinate(63),'W')
play(board,Coordinate(64),'B')
play(board,Coordinate(65),'W')
play(board,Coordinate(73),'W')
play(board,Coordinate(74),'B')
play(board,Coordinate(75),'W')
play(board,Coordinate(83),'W')
play(board,Coordinate(84),'B')
play(board,Coordinate(85),'W')
play(board,Coordinate(94),'W')


play(board,Coordinate(54),'W')