# Large game simulation
play(board,Coordinate(12),'W')
play(board,Coordinate(21),'W')
play(board,Coordinate(22),'W')
play(board,Coordinate(23),'W')
play(board,Coordinate(24),'W')
play(board,Coordinate(42),'B')
play(board,Coordinate(31),'W')
play(board,Coordinate(32),'B')
play(board,Coordinate(33),'B')
play(board,Coordinate(34),'B')

play(board,CoorContainer(coor=numToCoor("35")),'W')
play(board,CoorContainer(coor=numToCoor("41")),'W')
play(board,CoorContainer(coor=numToCoor("43")),'B')
play(board,CoorContainer(coor=numToCoor("44")),'W')
play(board,CoorContainer(coor=numToCoor("51")),'W')
play(board,CoorContainer(coor=numToCoor("52")),'B')
play(board,CoorContainer(coor=numToCoor("53")),'B')
play(board,CoorContainer(coor=numToCoor("55")),'W')
play(board,CoorContainer(coor=numToCoor("62")),'W')
play(board,CoorContainer(coor=numToCoor("63")),'W')
play(board,CoorContainer(coor=numToCoor("64")),'B')
play(board,CoorContainer(coor=numToCoor("65")),'W')
play(board,CoorContainer(coor=numToCoor("73")),'W')
play(board,CoorContainer(coor=numToCoor("74")),'B')
play(board,CoorContainer(coor=numToCoor("75")),'W')
play(board,CoorContainer(coor=numToCoor("83")),'W')
play(board,CoorContainer(coor=numToCoor("85")),'W')
play(board,CoorContainer(coor=numToCoor("84")),'B')
play(board,CoorContainer(coor=numToCoor("94")),'W')


play(board,CoorContainer(coor=numToCoor("54")),'W')